# AgentShell 設定ファイル例

[server]
url = "http://localhost:57575"
reconnect_interval = 5.0
heartbeat_interval = 30.0
connection_timeout = 10.0

[agents.claude_code]
executable = "claude"
timeout = 120.0
max_retries = 3
# working_directory = "/path/to/project"

[agents.openhands]
endpoint = "http://localhost:3000"
timeout = 300.0
max_retries = 2
# api_key = "your-api-key-here"

[coordination]
enable_interactive = true
enable_auto_requests = true
request_timeout = 30.0
max_concurrent_tasks = 5

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
# file = "/var/log/agentshell.log"