# AetherTerm Shell - 連携モード設定
# AIシェル + AetherTermサーバー連携

# 動作モード設定
mode = "connected"
debug = false
enable_ai = true

# AI サービス設定（独立動作）
[ai_service]
provider = "openai"  # openai, anthropic, local
api_key = ""  # 環境変数 AETHERTERM_AI_API_KEY で設定推奨
model = "gpt-4"
endpoint = ""  # カスタムエンドポイント（空の場合はプロバイダーのデフォルト）
timeout = 30
max_retries = 3

# AI機能設定
enable_command_analysis = true
enable_error_suggestions = true
enable_command_suggestions = true
max_command_history = 50

# サーバー接続設定（連携モードでは有効）
[server_connection]
enabled = true
server_url = "http://localhost:57575"
auto_connect = true
sync_interval = 30
reconnection_attempts = 5
reconnection_delay = 1

# 同期機能設定
sync_sessions = true
sync_ai_notifications = true
sync_command_history = false  # プライバシー考慮でデフォルトOFF

# ターミナル監視設定
[monitor]
buffer_size = 8192
poll_interval = 0.1
max_history = 1000
enable_output_capture = true
enable_input_capture = false

# セッション管理設定
[session]
session_timeout = 3600  # 1時間
max_sessions = 100
cleanup_interval = 300  # 5分
enable_persistence = true

# ログ設定
[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
file_path = ""  # 空の場合はファイル出力なし
max_file_size = 10485760  # 10MB
backup_count = 5

# OpenTelemetry設定
[telemetry]
service_name = "aetherterm-shell-connected"
service_version = "1.0.0"
environment = "development"
otlp_endpoint = "http://localhost:4317"
enable_tracing = true  # 連携モードではデフォルトON
enable_metrics = true
enable_log_instrumentation = true
trace_sample_rate = 1.0
metrics_export_interval = 30

# 環境変数による設定上書き例:
# AETHERTERM_MODE=connected
# AETHERTERM_AI_PROVIDER=openai
# AETHERTERM_AI_API_KEY=your-api-key
# AETHERTERM_AI_MODEL=gpt-4
# AETHERTERM_ENABLE_AI=true
# AETHERTERM_SERVER_ENABLED=true
# AETHERTERM_SERVER_URL=http://localhost:57575
# AETHERTERM_DEBUG=false