# AetherTerm Shell - デフォルト設定ファイル
# 独立したAIシェルシステム（サーバー依存なし）

# 動作モード設定
mode = "standalone"  # standalone, connected
debug = false
enable_ai = true
wrapper_socket_path = "/tmp/aetherterm_wrapper.sock"

# AI サービス設定（独立動作）
[ai_service]
provider = "openai"  # openai, anthropic, local
api_key = ""  # 環境変数 AETHERTERM_AI_API_KEY で設定推奨
model = "gpt-4"
endpoint = ""  # カスタムエンドポイント（空の場合はプロバイダーのデフォルト）
timeout = 30
max_retries = 3

# AI機能設定
enable_command_analysis = true
enable_error_suggestions = true
enable_command_suggestions = true
max_command_history = 50

# ターミナル監視設定
[monitor]
buffer_size = 8192
poll_interval = 0.1
max_history = 1000
enable_output_capture = true  # scriptと同様に標準出力に出力
enable_input_capture = false  # 入力の記録（プライバシー考慮でデフォルトOFF）

# セッション管理設定
[session]
session_timeout = 3600  # 1時間
max_sessions = 100
cleanup_interval = 300  # 5分
enable_persistence = true

# ログ設定
[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
file_path = ""  # 空の場合はファイル出力なし
max_file_size = 10485760  # 10MB
backup_count = 5

# OpenTelemetry設定
[telemetry]
service_name = "aetherterm-wrapper"
service_version = "1.0.0"
environment = "development"
otlp_endpoint = "http://localhost:4317"
enable_tracing = true
enable_metrics = true
enable_log_instrumentation = true
trace_sample_rate = 1.0
metrics_export_interval = 30

# サーバー接続設定（オプショナル）
[server_connection]
enabled = false  # デフォルトは無効（独立動作）
server_url = "http://localhost:57575"
auto_connect = true
sync_interval = 30
reconnection_attempts = 5
reconnection_delay = 1

# 同期機能設定
sync_sessions = true
sync_ai_notifications = true
sync_command_history = false  # プライバシー考慮でデフォルトOFF

# レガシー互換性のための設定（非推奨）
[aetherterm_sync]
server_url = "http://localhost:57575"
enable_sync = false  # 新設計では server_connection.enabled を使用
sync_interval = 30
reconnection_attempts = 5
reconnection_delay = 1

# 環境変数による設定上書き例（独立化対応）:
#
# 動作モード設定:
# AETHERTERM_MODE=standalone  # または connected
# AETHERTERM_DEBUG=true
# AETHERTERM_ENABLE_AI=true
#
# AI プロバイダー設定:
# AETHERTERM_AI_PROVIDER=openai  # openai, anthropic, local
# AETHERTERM_AI_API_KEY=your-api-key
# AETHERTERM_AI_MODEL=gpt-4
# AETHERTERM_AI_ENDPOINT=https://api.openai.com/v1  # カスタムエンドポイント
#
# サーバー連携設定（オプショナル）:
# AETHERTERM_SERVER_ENABLED=false  # サーバー連携の有効/無効
# AETHERTERM_SERVER_URL=http://localhost:57575
#
# テレメトリー設定:
# AETHERTERM_OTLP_ENDPOINT=http://localhost:4317
# AETHERTERM_SERVICE_NAME=aetherterm-shell
# AETHERTERM_ENVIRONMENT=production
#
# レガシー互換性（非推奨）:
# AETHERTERM_ENABLE_SYNC=false  # server_connection.enabled を使用推奨

# 使用例:
#
# スタンドアロンモード（AIのみ）:
# uv run aetherterm-shell --config standalone.toml
# または
# AETHERTERM_MODE=standalone uv run aetherterm-shell
#
# 連携モード（AI + サーバー）:
# uv run aetherterm-shell --config connected.toml
# または
# AETHERTERM_MODE=connected AETHERTERM_SERVER_ENABLED=true uv run aetherterm-shell